# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 09:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, '企业'), (1, '个体'), (2, '个人'), (3, '政府')], default=0, verbose_name='认证账户类型')),
            ],
            options={
                'verbose_name': '实名账户类型',
                'verbose_name_plural': '实名账户类型',
                'db_table': 'account_type',
            },
        ),
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='用户邮箱')),
                ('code', models.CharField(max_length=10, verbose_name='验证码')),
                ('verify_type', models.CharField(choices=[('authenticate', '实名认证'), ('forget', '忘记密码'), ('register', '注册激活')], max_length=30, verbose_name='验证类型')),
                ('send_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
                'db_table': 'email_vc',
            },
        ),
        migrations.CreateModel(
            name='IDPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='user/id_picture', verbose_name='手持身份证照片')),
            ],
            options={
                'verbose_name': '手持身份证照片',
                'verbose_name_plural': '手持身份证照片',
                'db_table': 'id_picture',
            },
        ),
        migrations.CreateModel(
            name='MemberAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
            ],
            options={
                'verbose_name': '会员地址',
                'verbose_name_plural': '会员地址',
                'db_table': 'member_address',
            },
        ),
        migrations.CreateModel(
            name='MemberFollowProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '支持者与项目关联信息',
                'verbose_name_plural': '支持者与项目关联信息',
                'db_table': 'member_follow_project',
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('user_type', models.IntegerField(choices=[(0, '个人'), (1, '企业')], default=0, verbose_name='账户类型')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '会员信息',
                'verbose_name_plural': '会员信息',
                'db_table': 'members',
            },
        ),
        migrations.CreateModel(
            name='RealNameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=20, verbose_name='真实姓名')),
                ('id_card', models.CharField(max_length=18, verbose_name='身份证号码')),
                ('phone_num', models.CharField(max_length=13, verbose_name='电话号码')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.MemberProfile', verbose_name='所属会员')),
            ],
            options={
                'verbose_name': '实名身份信息',
                'verbose_name_plural': '实名身份信息',
                'db_table': 'real_name_info',
            },
        ),
        migrations.AddField(
            model_name='memberfollowproject',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.MemberProfile', verbose_name='支持者'),
        ),
        migrations.AddField(
            model_name='memberfollowproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='支持项目'),
        ),
        migrations.AddField(
            model_name='memberaddress',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.MemberProfile', verbose_name='会员'),
        ),
        migrations.AddField(
            model_name='idpicture',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.MemberProfile', verbose_name='所属会员'),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.MemberProfile', verbose_name='所属会员'),
        ),
    ]
