# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-09 11:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountNumInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_num', models.CharField(max_length=11, verbose_name='易付宝企业账号')),
                ('id_card', models.CharField(max_length=18, verbose_name='法人身份证号')),
            ],
            options={
                'verbose_name': '收款账号及身份核实',
                'verbose_name_plural': '收款账号及身份核实',
            },
        ),
        migrations.CreateModel(
            name='InitiatorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_intro', models.CharField(max_length=100, verbose_name='自我介绍')),
                ('detail_intro', models.TextField(verbose_name='详细自我介绍')),
                ('mobile', models.CharField(max_length=11, verbose_name='联系电话')),
                ('service_phone', models.CharField(max_length=11, verbose_name='客服电话')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发起项目的用户')),
            ],
            options={
                'verbose_name': '发起人信息',
                'verbose_name_plural': '发起人信息',
            },
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='项目1', max_length=50, verbose_name='众筹项目名字')),
                ('desc', models.CharField(max_length=200, verbose_name='项目一句话简述')),
                ('fav_num', models.IntegerField(verbose_name='关注人数')),
                ('target_money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='目标金额')),
                ('raised_money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='已筹金额')),
                ('create_time', models.DateField(verbose_name='创建日期')),
                ('category', models.CharField(choices=[('public_welfare', '公益'), ('technology', '科技'), ('agriculture', '农业'), ('design', '设计')], default='technology', max_length=10, verbose_name='项目分类')),
                ('tage', models.CharField(choices=[('digital', '数码'), ('computer', '电脑'), ('mobile', '手机')], default='mobile', max_length=10, verbose_name='项目标签')),
                ('active_status', models.CharField(choices=[('0', '审核中'), ('1', '众筹中'), ('2', '已结束')], default='0', max_length=10, verbose_name='项目状态')),
                ('project_img', models.ImageField(default='project_img/default.png', upload_to='project_img/%Y/%m', verbose_name='项目图片')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.InitiatorInfo', verbose_name='项目发起人或机构')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发起项目的用户')),
            ],
            options={
                'verbose_name': '项目信息',
                'verbose_name_plural': '项目信息',
            },
        ),
        migrations.CreateModel(
            name='RepayInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reality', '实物回报'), ('virtual', '虚拟物品回报')], default='reality', max_length=10, verbose_name='回报类型')),
                ('support_money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支持金额')),
                ('repay_content', models.TextField(verbose_name='回报内容')),
                ('repay_img', models.ImageField(default='repay_img/default.png', upload_to='repay_img/%Y/%m', verbose_name='项目图片')),
                ('repay_num', models.IntegerField(verbose_name='回报数量')),
                ('is_limit_buy', models.CharField(choices=[('0', '不限购'), ('1', '限购')], max_length=10, verbose_name='单笔限购')),
                ('limit_buy_num', models.IntegerField(verbose_name='限购数量')),
                ('freight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='运费')),
                ('receipt', models.CharField(choices=[('0', '不可开发票'), ('1', '可开发票')], max_length=10, verbose_name='是否开发票')),
                ('repay_time', models.IntegerField(verbose_name='回报时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectInfo', verbose_name='众筹项目')),
            ],
            options={
                'verbose_name': '回报信息',
                'verbose_name_plural': '回报信息',
            },
        ),
        migrations.AddField(
            model_name='accountnuminfo',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectInfo', verbose_name='众筹项目'),
        ),
        migrations.AddField(
            model_name='accountnuminfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='收款的用户'),
        ),
    ]
