# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-09 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='active_status',
            field=models.CharField(choices=[('0', '审核中'), ('2', '已结束'), ('1', '众筹中')], default='0', max_length=10, verbose_name='项目状态'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='category',
            field=models.CharField(choices=[('agriculture', '农业'), ('technology', '科技'), ('design', '设计'), ('public_welfare', '公益')], default='technology', max_length=10, verbose_name='项目分类'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='tage',
            field=models.CharField(choices=[('mobile', '手机'), ('digital', '数码'), ('computer', '电脑')], default='mobile', max_length=10, verbose_name='项目标签'),
        ),
    ]
