# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-09 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180509_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiatorinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='initiator',
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='brief_intro',
            field=models.CharField(default='自我介绍', max_length=100, verbose_name='自我介绍'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='detail_intro',
            field=models.TextField(default='详细自我介绍', verbose_name='详细自我介绍'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='mobile',
            field=models.CharField(default='123', max_length=11, verbose_name='联系电话'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='service_phone',
            field=models.CharField(default='123', max_length=11, verbose_name='客服电话'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='category',
            field=models.CharField(choices=[('public_welfare', '公益'), ('technology', '科技'), ('agriculture', '农业'), ('design', '设计')], default='technology', max_length=10, verbose_name='项目分类'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='tage',
            field=models.CharField(choices=[('computer', '电脑'), ('mobile', '手机'), ('digital', '数码')], default='mobile', max_length=10, verbose_name='项目标签'),
        ),
        migrations.DeleteModel(
            name='InitiatorInfo',
        ),
    ]
