# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-09 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20180509_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='total_time',
            field=models.IntegerField(default=30, verbose_name='筹资天数'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='category',
            field=models.CharField(choices=[('agriculture', '农业'), ('technology', '科技'), ('design', '设计'), ('public_welfare', '公益')], default='technology', max_length=10, verbose_name='项目分类'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='tage',
            field=models.CharField(choices=[('computer', '电脑'), ('digital', '数码'), ('mobile', '手机')], default='mobile', max_length=10, verbose_name='项目标签'),
        ),
        migrations.AlterField(
            model_name='repayinfo',
            name='limit_buy_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='限购数量'),
        ),
    ]
