# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-10 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20180509_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='support_people',
            field=models.IntegerField(default=0, verbose_name='支持人数'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='active_status',
            field=models.CharField(choices=[('1', '众筹中'), ('2', '众筹成功'), ('0', '即将开始')], default='0', max_length=10, verbose_name='项目状态'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='category',
            field=models.CharField(choices=[('technology', '科技'), ('culture', '文化'), ('public_welfare', '公益'), ('design', '设计'), ('agriculture', '农业')], default='technology', max_length=20, verbose_name='项目分类'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='tage',
            field=models.CharField(choices=[('mobile', '手机'), ('digital', '数码'), ('computer', '电脑')], default='mobile', max_length=10, verbose_name='项目标签'),
        ),
    ]
