# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-10 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20180510_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='detail_img',
            field=models.ImageField(default='detail_img/default.png', upload_to='detail_img/%Y/%m', verbose_name='项目详情'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='main_img',
            field=models.ImageField(default='main_img/default.png', upload_to='main_img/%Y/%m', verbose_name='项目头图'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='active_status',
            field=models.CharField(choices=[('1', '众筹中'), ('0', '即将开始'), ('2', '众筹成功')], default='0', max_length=10, verbose_name='项目状态'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='category',
            field=models.CharField(choices=[('technology', '科技'), ('public_welfare', '公益'), ('culture', '文化'), ('design', '设计'), ('agriculture', '农业')], default='technology', max_length=20, verbose_name='项目分类'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='tage',
            field=models.CharField(choices=[('computer', '电脑'), ('mobile', '手机'), ('digital', '数码')], default='mobile', max_length=10, verbose_name='项目标签'),
        ),
    ]
