# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-10 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20180510_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='category',
            field=models.CharField(choices=[('design', '设计'), ('public_welfare', '公益'), ('technology', '科技'), ('culture', '文化'), ('agriculture', '农业')], default='technology', max_length=20, verbose_name='项目分类'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='create_time',
            field=models.DateField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='fav_num',
            field=models.IntegerField(default=0, verbose_name='关注人数'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='raised_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='已筹金额'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='tage',
            field=models.CharField(choices=[('digital', '数码'), ('mobile', '手机'), ('computer', '电脑')], default='mobile', max_length=10, verbose_name='项目标签'),
        ),
    ]
