# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-10 15:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20180510_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='active_status',
            field=models.CharField(choices=[('2', '众筹成功'), ('1', '众筹中'), ('0', '即将开始')], default='0', max_length=10, verbose_name='项目状态'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发起项目的用户'),
        ),
    ]
