# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-11 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20180510_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='active_status',
            field=models.CharField(choices=[('1', '众筹中'), ('2', '众筹成功'), ('0', '即将开始')], default='0', max_length=10, verbose_name='项目状态'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='category',
            field=models.CharField(choices=[('technology', '科技'), ('culture', '文化'), ('design', '设计'), ('public_welfare', '公益'), ('agriculture', '农业')], default='technology', max_length=20, verbose_name='项目分类'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='tage',
            field=models.CharField(choices=[('computer', '电脑'), ('digital', '数码'), ('mobile', '手机')], default='mobile', max_length=10, verbose_name='项目标签'),
        ),
        migrations.AlterField(
            model_name='repayinfo',
            name='limit_buy_num',
            field=models.IntegerField(default=1, verbose_name='限购数量'),
        ),
    ]
