# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-12 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20180512_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='category',
            field=models.CharField(choices=[('technology', '科技'), ('culture', '文化'), ('public_welfare', '公益'), ('design', '设计'), ('agriculture', '农业')], default='technology', max_length=20, verbose_name='项目分类'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='tage',
            field=models.CharField(choices=[('mobile', '手机'), ('computer', '电脑'), ('digital', '数码')], default='mobile', max_length=10, verbose_name='项目标签'),
        ),
    ]
