# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-12 19:16
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0010_auto_20180512_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='关注时间')),
            ],
            options={
                'verbose_name_plural': '用户关注项目表',
                'verbose_name': '用户关注项目表',
            },
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='active_status',
            field=models.CharField(choices=[('0', '即将开始'), ('2', '众筹成功'), ('1', '众筹中')], default='0', max_length=10, verbose_name='项目状态'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='category',
            field=models.CharField(choices=[('design', '设计'), ('agriculture', '农业'), ('culture', '文化'), ('public_welfare', '公益'), ('technology', '科技')], default='technology', max_length=20, verbose_name='项目分类'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='tage',
            field=models.CharField(choices=[('digital', '数码'), ('computer', '电脑'), ('mobile', '手机')], default='mobile', max_length=10, verbose_name='项目标签'),
        ),
        migrations.AddField(
            model_name='userfavproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectInfo', verbose_name='被关注的项目'),
        ),
        migrations.AddField(
            model_name='userfavproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关注的用户'),
        ),
    ]
