# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-13 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20180512_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='active_status',
            field=models.CharField(choices=[('2', '众筹成功'), ('1', '众筹中'), ('0', '即将开始')], default='0', max_length=10, verbose_name='项目状态'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='category',
            field=models.CharField(choices=[('public_welfare', '公益'), ('technology', '科技'), ('agriculture', '农业'), ('design', '设计'), ('culture', '文化')], default='technology', max_length=20, verbose_name='项目分类'),
        ),
    ]
