# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-11 07:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180511_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercertify',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='认证邮箱'),
        ),
        migrations.AlterField(
            model_name='usercertify',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='认证的用户'),
        ),
        migrations.AlterField(
            model_name='usercertify',
            name='usercertify_type',
            field=models.CharField(choices=[('BusinessCompany', '商业公司'), ('IndividualIndustryAndCommerce', '个体工商户'), ('GovernmentAndNoprofitOrganizations', '政府及非营利组织'), ('PersonalManagement', '个人经营')], max_length=100, verbose_name='实名认证账户类型'),
        ),
    ]
