# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-12 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180512_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercertify',
            name='usercertify_type',
            field=models.CharField(choices=[('BusinessCompany', '商业公司'), ('PersonalManagement', '个人经营'), ('GovernmentAndNoprofitOrganizations', '政府及非营利组织'), ('IndividualIndustryAndCommerce', '个体工商户')], max_length=100, verbose_name='实名认证账户类型'),
        ),
    ]
