# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-14 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20180514_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercertify',
            name='usercertify_type',
            field=models.CharField(choices=[('GovernmentAndNoprofitOrganizations', '政府及非营利组织'), ('PersonalManagement', '个人经营'), ('IndividualIndustryAndCommerce', '个体工商户'), ('BusinessCompany', '商业公司')], max_length=100, verbose_name='实名认证账户类型'),
        ),
    ]
