# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-11 16:37
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0009_auto_20180512_0037'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0006_auto_20180512_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('order_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='订单编号')),
                ('need_receipt', models.CharField(choices=[('0', '无需发票'), ('1', '需要发票')], default='0', max_length=10, verbose_name='是否开发票')),
                ('receipt_head', models.CharField(default='', max_length=100, verbose_name='发票抬头')),
                ('remarks', models.CharField(default='', max_length=300, verbose_name='订单备注')),
                ('createtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('repay_count', models.IntegerField(default=1, verbose_name='购买数量')),
                ('freight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='运费')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='支持总价')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='优惠价格')),
                ('pay_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='支付价格')),
                ('address', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.UserAddress', verbose_name='订单的收货地址')),
                ('repayinfo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project.RepayInfo', verbose_name='订单的购买回报信息')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='订单用户')),
            ],
            options={
                'verbose_name': '回报订单信息',
                'verbose_name_plural': '回报订单信息',
            },
        ),
    ]
