# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-12 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='order_status',
            field=models.CharField(choices=[('1', '待支付'), ('2', '待发货'), ('3', '待收货'), ('4', '待评价'), ('5', '已完成')], default='1', max_length=10, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserAddress', verbose_name='订单的收货地址'),
        ),
    ]
