# Generated by Django 2.0.5 on 2018-05-15 10:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_company', models.ImageField(default='image_company/default.png', upload_to='image_company/%Y/%m')),
                ('company_name', models.CharField(max_length=20, verbose_name='公司名字')),
                ('desc', models.CharField(max_length=200, verbose_name='公司简介')),
                ('phone', models.CharField(max_length=11, verbose_name='公司电话')),
                ('usename', models.CharField(max_length=10, verbose_name='发起人姓名')),
                ('userdesc', models.CharField(max_length=100, verbose_name='自我介绍')),
                ('userdetail', models.CharField(max_length=100, verbose_name='详细自我介绍')),
                ('mobile', models.CharField(max_length=11, verbose_name='电话')),
            ],
            options={
                'verbose_name': '公司详情',
                'verbose_name_plural': '公司详情',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='标签')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='image/default.png', upload_to='image/%Y/%m')),
                ('name', models.CharField(max_length=50, verbose_name='众筹商品名')),
                ('detail', models.CharField(blank=True, max_length=300, null=True, verbose_name='备注')),
                ('url', models.URLField(default='#', verbose_name='访问链接')),
                ('money', models.CharField(default=0, max_length=15, verbose_name='目标资金')),
                ('end_money', models.CharField(default=0, max_length=15, verbose_name='已筹集资金')),
                ('supporter', models.IntegerField(default=0, verbose_name='支持人数')),
                ('is_collections', models.BooleanField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否收藏')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_follow', models.BooleanField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否關注')),
                ('end_time', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='結束时间')),
                ('time', models.IntegerField(null=True, verbose_name='天数')),
                ('status', models.CharField(choices=[('jjks', '即将开始'), ('zcz', '众筹中'), ('zccg', '众筹成功')], default='jjks', max_length=30)),
                ('image_head', models.ImageField(default='image_head/default.png', upload_to='image_head/%Y/%m')),
                ('image_body', models.ImageField(default='image_head/default.png', upload_to='image_body/%Y/%m')),
                ('peoples', models.IntegerField(verbose_name='关注人数')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Company')),
            ],
            options={
                'verbose_name': '众筹商品',
                'verbose_name_plural': '众筹商品',
            },
        ),
        migrations.CreateModel(
            name='ProjectName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pyname', models.CharField(max_length=50, verbose_name='商品类别名')),
                ('desc', models.CharField(max_length=100, verbose_name='列表解释')),
            ],
            options={
                'verbose_name': '商品类别',
                'verbose_name_plural': '商品类别',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='projectname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectName'),
        ),
    ]
