# Generated by Django 2.0.5 on 2018-05-15 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180515_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.ProjectName'),
        ),
    ]
