# Generated by Django 2.0.5 on 2018-05-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20180515_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='peoples',
            field=models.IntegerField(null=True, verbose_name='关注人数'),
        ),
    ]
