# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-14 13:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('image', models.ImageField(upload_to='banner/%Y/%m', verbose_name='轮播图')),
                ('url', models.URLField(verbose_name='访问地址')),
                ('index', models.IntegerField(default=100, verbose_name='顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='PorjectTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='标签名')),
            ],
            options={
                'verbose_name': '项目标签',
                'verbose_name_plural': '项目标签',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='项目名称')),
                ('remark', models.CharField(max_length=255, verbose_name='简介')),
                ('money', models.BigIntegerField(default=0, verbose_name='金额')),
                ('day', models.IntegerField(default=0, verbose_name='天数')),
                ('status', models.CharField(choices=[('0', '即将开始'), ('1', '众筹中'), ('2', '众筹成功'), ('3', '众筹失败')], default=0, max_length=1, verbose_name='众筹状态')),
                ('deploydate', models.CharField(default=0, max_length=10, verbose_name='部署日期')),
                ('supportmoney', models.IntegerField(default=0, verbose_name='支持金额')),
                ('supporter', models.IntegerField(default=0, verbose_name='支持者数量')),
                ('completion', models.IntegerField(default=0, verbose_name='完成数量')),
                ('memberid', models.IntegerField(default=0, verbose_name='会员id')),
                ('createdate', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='创建时间')),
                ('stopdate', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='截止日期')),
                ('follower', models.IntegerField(default=0, verbose_name='支持者数量')),
                ('cash', models.IntegerField(default=0, verbose_name='已筹金额')),
                ('Target_amount', models.IntegerField(default=0, verbose_name='目标金额')),
                ('reach', models.IntegerField(default=0, verbose_name='达成进度')),
                ('send', models.CharField(default=0, max_length=10, verbose_name='配送运费')),
                ('image', models.ImageField(upload_to='image/%Y/%m', verbose_name='项目图片')),
                ('info', models.CharField(default='', max_length=400, verbose_name='一句话简介')),
                ('infos', models.CharField(default='', max_length=2000, verbose_name='详细介绍')),
                ('infoimage', models.ImageField(upload_to='image/%Y/%m', verbose_name='详情图片')),
                ('my_info', models.CharField(max_length=2000, verbose_name='自我介绍')),
                ('my_infos', models.CharField(max_length=2000, verbose_name='详细自我介绍')),
                ('phone', models.IntegerField(blank=True, default=0, null=True, verbose_name='手机号')),
                ('service', models.IntegerField(blank=True, null=True, verbose_name='客服电话')),
            ],
            options={
                'verbose_name': '项目信息',
                'verbose_name_plural': '项目信息',
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='项目类型')),
                ('remark', models.CharField(max_length=255, verbose_name='描述')),
            ],
            options={
                'verbose_name': '项目类型',
                'verbose_name_plural': '项目类型',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='众筹状态')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='项目id')),
            ],
            options={
                'verbose_name': '项目状态',
                'verbose_name_plural': '项目状态',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.ProjectType', verbose_name='项目类型'),
        ),
        migrations.AddField(
            model_name='porjecttag',
            name='pid',
            field=models.ManyToManyField(to='project.Project', verbose_name='项目标签'),
        ),
    ]
