# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-15 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_type', models.CharField(choices=[('0', '实物回报'), ('1', '虚拟物品回报')], default=0, max_length=1, verbose_name='回报类型')),
                ('supportmoney', models.IntegerField(default=0, verbose_name='支持金额')),
                ('content', models.CharField(max_length=2000, verbose_name='回报内容')),
                ('retimage', models.ImageField(upload_to='retimage/%Y/%m', verbose_name='回报图片')),
                ('retnum', models.IntegerField(default=0, verbose_name='回报数量')),
                ('count', models.IntegerField(default=0, verbose_name='单笔限购')),
                ('freight', models.IntegerField(default=0, verbose_name='运费')),
                ('invoice', models.CharField(choices=[('0', '不可开发票'), ('1', '可开发票')], max_length=1, verbose_name='发票')),
                ('rtndate', models.IntegerField(default=1, verbose_name='回报时间')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='关联项目')),
            ],
        ),
    ]
