# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 12:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='名称')),
                ('is_active', models.BooleanField(choices=[(1, '是'), (0, '否')], default=0, verbose_name='是否认证')),
                ('describe', models.CharField(blank=True, max_length=300, null=True, verbose_name='描述')),
                ('mobile', models.CharField(max_length=13, verbose_name='联系电话')),
            ],
            options={
                'verbose_name_plural': '公司信息',
                'verbose_name': '公司信息',
            },
        ),
        migrations.CreateModel(
            name='TProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=255, verbose_name='项目名称')),
                ('image', models.ImageField(upload_to='image/%Y/%m', verbose_name='图片')),
                ('describe', models.CharField(blank=True, max_length=300, null=True, verbose_name='描述')),
                ('money', models.BigIntegerField(verbose_name='众筹金额')),
                ('_date', models.CharField(db_column='date', max_length=100, verbose_name='众筹天数')),
                ('status', models.IntegerField(choices=[(0, '即将开始'), (1, '众筹中'), (2, '众筹成功'), (3, '众筹失败')], default=0, verbose_name='状态')),
                ('daploydate', models.DateField(verbose_name='开始日期')),
                ('is_collection', models.BooleanField(choices=[(1, '是'), (0, '否')], default=0, verbose_name='是否收藏')),
                ('is_category', models.CharField(choices=[('kj', '科技'), ('sj', '设计'), ('ny', '农业'), ('qt', '其他')], default='科技', max_length=2, verbose_name='类别')),
                ('is_follow', models.BooleanField(choices=[(1, '是'), (0, '否')], default=0, verbose_name='是否关注')),
                ('enddate', models.DateField(verbose_name='截止日期')),
                ('supportmoney', models.BigIntegerField(default=0, verbose_name='已筹资金')),
                ('supporter', models.IntegerField(default=0, verbose_name='投资人数')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发起会员')),
            ],
            options={
                'verbose_name_plural': '众筹项目表',
                'db_table': 'crowfund_project',
                'verbose_name': '众筹项目表',
            },
        ),
        migrations.CreateModel(
            name='TProjectTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.ForeignKey(blank=True, db_column='projectid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.TProject', verbose_name='产品id')),
            ],
            options={
                'verbose_name_plural': '产品标签',
                'db_table': 't_project_tag',
                'verbose_name': '产品标签',
            },
        ),
        migrations.CreateModel(
            name='TProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.ForeignKey(blank=True, db_column='projectid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.TProject')),
            ],
            options={
                'verbose_name_plural': '产品类型',
                'db_table': 't_project_type',
                'verbose_name': '产品类型',
            },
        ),
        migrations.CreateModel(
            name='TTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': '标签',
                'db_table': 't_tag',
                'verbose_name': '标签',
            },
        ),
        migrations.CreateModel(
            name='TType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': '类型',
                'db_table': 't_type',
                'verbose_name': '类型',
            },
        ),
        migrations.AddField(
            model_name='tprojecttype',
            name='typeid',
            field=models.ForeignKey(blank=True, db_column='typeid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.TType'),
        ),
        migrations.AddField(
            model_name='tprojecttag',
            name='tagid',
            field=models.ForeignKey(blank=True, db_column='tagid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.TTag', verbose_name='标签id'),
        ),
        migrations.AddField(
            model_name='company',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.TProject', verbose_name='公司商品'),
        ),
    ]
