# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tproject',
            name='_date',
        ),
        migrations.AddField(
            model_name='tproject',
            name='day',
            field=models.IntegerField(null=True, verbose_name='众筹天数'),
        ),
    ]
