# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-14 13:36
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='真实姓名')),
                ('image', models.ImageField(upload_to='image/%Y/%m', verbose_name='头像')),
                ('user_type', models.CharField(choices=[('0', '个人'), ('1', '企业')], max_length=30, verbose_name='用户类型')),
                ('loginacct', models.CharField(blank=True, max_length=255, null=True, verbose_name='登录地址')),
                ('authstatu', models.CharField(choices=[('0', '未实名认证'), ('1', '实名认证申请中'), ('2', '已实名认证')], max_length=1, verbose_name='实名认证状态')),
                ('accttypes', models.CharField(choices=[('0', '企业'), ('1', '个体'), ('2', '个人'), ('3', '政府')], max_length=1, verbose_name='企业类型')),
                ('base_id', models.IntegerField(default=0, verbose_name='翼支付账号')),
                ('user_id', models.IntegerField(default=0, verbose_name='身份证号')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='项目')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000, verbose_name='广告名')),
                ('icon', models.ImageField(default='', upload_to='image/%Y/%m', verbose_name='图片')),
                ('status', models.CharField(choices=[('0', '草稿，'), ('1', '未审核，'), ('2', '审核完成，'), ('3', '发布')], max_length=1, verbose_name='企业类型')),
                ('url', models.CharField(max_length=2000, verbose_name='链接地址')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
            ],
            options={
                'verbose_name': '项目广告',
                'verbose_name_plural': '项目广告',
            },
        ),
    ]
