# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-11 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='url',
        ),
    ]
