# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 14:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('status', models.CharField(blank=True, max_length=1, null=True, verbose_name='支付状态')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='地址')),
                ('invoice', models.CharField(blank=True, max_length=1, null=True, verbose_name='发票')),
                ('invoictitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='发票抬头')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '订单',
                'verbose_name': '订单',
            },
        ),
    ]
