# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-15 09:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='回报内容')),
                ('type', models.CharField(choices=[(0, '实物回报'), (1, '虚拟物品回报')], max_length=1)),
                ('supportmoney', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支持单价')),
                ('count', models.CharField(max_length=20, verbose_name='回报数量')),
                ('signalpurchase', models.CharField(max_length=20)),
                ('purchase', models.CharField(max_length=20)),
                ('freight', models.CharField(max_length=11, verbose_name='运费')),
                ('invoice', models.CharField(choices=[(0, '不开发票'), (1, '开发票')], max_length=1)),
                ('rtndate', models.DateTimeField(default=datetime.datetime.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='项目id')),
            ],
        ),
    ]
