# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-15 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repay',
            name='residue',
            field=models.CharField(default=1, max_length=10, verbose_name='剩余天数'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repay',
            name='freight',
            field=models.IntegerField(choices=[(0, '包邮'), (1, 10)], default=0, verbose_name='运费'),
        ),
    ]
