# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-14 20:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicDisplay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberaddress',
            name='name',
            field=models.CharField(default=datetime.datetime(2018, 5, 14, 20, 43, 52, 632801), max_length=255, verbose_name='收件人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberaddress',
            name='phone',
            field=models.CharField(default=datetime.datetime(2018, 5, 14, 20, 43, 58, 959613), max_length=255, verbose_name='电话'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.CharField(choices=[('0', '不开发票'), ('1', '开发票')], default=0, max_length=1, verbose_name='发票'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoictitle',
            field=models.CharField(default='', max_length=255, verbose_name='发票抬头'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.CharField(default='', max_length=255, verbose_name='订单数量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='remark',
            field=models.CharField(default='', max_length=255, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', '待付款'), ('1', '交易完成'), ('9', '交易关闭')], default=0, max_length=1, verbose_name='状态'),
        ),
    ]
