# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-12 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAdress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('rev_person', models.CharField(max_length=30, verbose_name='收货人')),
                ('rev_phone', models.CharField(max_length=20, verbose_name='收货人电话')),
                ('rev_adress', models.CharField(max_length=100, verbose_name='收货地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserMsg', verbose_name='使用者')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_bill', models.SmallIntegerField(choices=[(0, '不开发票'), (1, '开发票')], default=0, verbose_name='是否发票')),
                ('remarksr', models.CharField(max_length=100, verbose_name='备注')),
                ('com_repay', models.CharField(max_length=200, verbose_name='回报内容')),
                ('num_repay', models.IntegerField(default=1, verbose_name='回报数量')),
                ('price_support', models.IntegerField(default=1, verbose_name='支持单价')),
                ('send_way', models.SmallIntegerField(choices=[(0, '免运费'), (1, '货到付款'), (2, '买家承担')], default=0, verbose_name='商品状态')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ReProduct', verbose_name='回报商品')),
                ('start_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.CompanyMsg', verbose_name='发起人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserMsg', verbose_name='下单者')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
