# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-12 18:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '支持-项目表',
                'verbose_name_plural': '支持-项目表',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(max_length=255, verbose_name='订单数量')),
                ('create_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('money', models.IntegerField(verbose_name='价格')),
                ('rtncount', models.IntegerField(verbose_name='返回数量')),
                ('status', models.CharField(choices=[('0', '待付款'), ('1', '交易完成'), ('9', '交易关闭')], max_length=1, verbose_name='状态')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
                ('invoice', models.CharField(choices=[('0', '不开发票'), ('1', '开发票')], max_length=1, verbose_name='发票')),
                ('invoictitle', models.CharField(max_length=255, verbose_name='发票抬头')),
                ('remark', models.CharField(max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='项目名称')),
                ('remark', models.CharField(max_length=255, verbose_name='简介')),
                ('money', models.BigIntegerField(verbose_name='筹资金额（元）')),
                ('day', models.IntegerField(verbose_name='筹资天数(天)')),
                ('status', models.CharField(choices=[('0', '即将开始'), ('1', '众筹中'), ('2', '众筹成功'), ('3', '众筹失败')], default='0', max_length=20, verbose_name='众筹状态')),
                ('deploydate', models.DateTimeField(default=datetime.datetime.now, max_length=10, verbose_name='部署日期')),
                ('supportmoney', models.BigIntegerField(default=0, verbose_name='支持资金')),
                ('completion', models.CharField(choices=[('0', '未完成'), ('1', '已完成')], default='0', max_length=1, verbose_name='是否完成')),
                ('createdate', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('project_head_img', models.ImageField(upload_to='head_img/%Y/%m', verbose_name='项目头图')),
                ('project_detail', models.ImageField(upload_to='detail/%Y/%m', verbose_name='项目详情')),
            ],
            options={
                'verbose_name': '众筹项目',
                'verbose_name_plural': '众筹项目',
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', '实物回报'), ('1', '虚拟物品回报')], max_length=1, verbose_name='回报类型')),
                ('supportmoney', models.IntegerField(verbose_name='支持资金')),
                ('content', models.CharField(max_length=255, verbose_name='回报内容')),
                ('explain', models.ImageField(max_length=255, upload_to='explain/%Y/%m', verbose_name='说明图片')),
                ('count', models.IntegerField(verbose_name='回报数量')),
                ('purchase', models.IntegerField(default=1, verbose_name='单笔限购')),
                ('freight', models.IntegerField(verbose_name='货运')),
                ('invoice', models.CharField(choices=[('0', '不开发票'), ('1', '开发票')], max_length=1, verbose_name='发票')),
                ('rtndate', models.DateTimeField(verbose_name='回报时间')),
                ('projectid', models.ForeignKey(max_length=11, on_delete=django.db.models.deletion.CASCADE, to='permit.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '回报表',
                'verbose_name_plural': '回报表',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='标签类型')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Twolable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='二级标签')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permit.Tag', verbose_name='标签表')),
            ],
            options={
                'verbose_name': '二级标签',
                'verbose_name_plural': '二级标签',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('remark', models.CharField(max_length=255, verbose_name='描述')),
            ],
            options={
                'verbose_name': '类别表',
                'verbose_name_plural': '类别表',
            },
        ),
    ]
