# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-15 09:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, verbose_name='项目名字')),
                ('remark', models.CharField(max_length=100, verbose_name='项目描述')),
                ('in_short', models.CharField(max_length=100, verbose_name='一句话简介')),
                ('status', models.IntegerField(choices=[(0, '即将开始'), (1, '众筹中'), (2, '众筹失败'), (3, '众筹成功')], default=0, verbose_name='众筹状态')),
                ('target_money', models.IntegerField(default=0, verbose_name='目标金额')),
                ('support_money', models.IntegerField(default=0, verbose_name='筹集金额')),
                ('project_title', models.ImageField(upload_to='project/title', verbose_name='项目头图')),
                ('project_desc', models.ImageField(upload_to='project/desc', verbose_name='项目详情图')),
                ('completion', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='完成进度')),
                ('supporters', models.IntegerField(default=0, verbose_name='支持人数')),
                ('period', models.IntegerField(default=0, verbose_name='筹集天数')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
                ('deploy_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='上线日期')),
                ('introduce', models.CharField(max_length=80, verbose_name='自我介绍')),
                ('introduce_desc', models.CharField(max_length=100, verbose_name='详细自我介绍')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('customer_phone', models.CharField(max_length=11, verbose_name='客服电话')),
            ],
            options={
                'verbose_name': '项目表',
                'verbose_name_plural': '项目表',
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='类型')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '类型',
                'verbose_name_plural': '类型',
            },
        ),
        migrations.CreateModel(
            name='TagFirst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, verbose_name='标签')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '一级标签表',
                'verbose_name_plural': '一级标签表',
            },
        ),
        migrations.CreateModel(
            name='TagSecond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, verbose_name='标签')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '二级标签表',
                'verbose_name_plural': '二级标签表',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='tag1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.TagFirst'),
        ),
        migrations.AddField(
            model_name='project',
            name='tag2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.TagSecond'),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectType', verbose_name='项目分类'),
        ),
    ]
