# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 09:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='项目名称')),
                ('remark', models.CharField(max_length=255, verbose_name='项目描述')),
                ('target_money', models.IntegerField(default=0, verbose_name='目标金额')),
                ('support_money', models.IntegerField(default=0, verbose_name='已筹金额')),
                ('project_cover', models.ImageField(upload_to='project/cover', verbose_name='项目头图')),
                ('project_info', models.ImageField(upload_to='project/info', verbose_name='项目详情图')),
                ('completion', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='完成进度')),
                ('supporters', models.IntegerField(default=0, verbose_name='支持人数')),
                ('status', models.IntegerField(choices=[(0, '即将开始'), (1, '众筹中'), (2, '众筹成功'), (3, '众筹失败')], default=0, verbose_name='项目状态')),
                ('period', models.IntegerField(default=0, verbose_name='筹集天数')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
                ('deploy_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='上线日期')),
                ('type', models.IntegerField(choices=[(0, '科技'), (1, '设计'), (2, '公益'), (3, '农业'), (4, '文化')], default=0, verbose_name='项目分类')),
                ('a_word_intro', models.CharField(default='一句话介绍', max_length=50, verbose_name='一句话自我介绍')),
                ('self_intro', models.TextField(default='详细介绍', verbose_name='详细自我介绍')),
                ('phone_number', models.CharField(max_length=13, verbose_name='联系电话')),
                ('service_number', models.CharField(max_length=13, verbose_name='客服电话')),
            ],
            options={
                'verbose_name': '项目信息',
                'verbose_name_plural': '项目信息',
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='SubTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_tag_name', models.CharField(max_length=10, verbose_name='二级标签名称')),
            ],
            options={
                'verbose_name': '二级标签',
                'verbose_name_plural': '二级标签',
                'db_table': 'sub_tag',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=10, verbose_name='标签名称')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '一级标签',
                'verbose_name_plural': '一级标签',
                'db_table': 'tag',
            },
        ),
        migrations.AddField(
            model_name='subtag',
            name='parent_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Tag', verbose_name='关联父标签'),
        ),
    ]
