# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.MemberProfile', verbose_name='发起人'),
        ),
    ]
