# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20180514_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='completion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='完成进度'),
        ),
    ]
