# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20180514_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='completion',
            field=models.IntegerField(default=0, verbose_name='完成进度'),
        ),
    ]
