# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-15 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20180515_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='one_order_limit',
            field=models.IntegerField(default=1, verbose_name='单笔限购数量'),
        ),
    ]
