# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-11 00:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projectmodels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('image', models.ImageField(default='', upload_to='projects/%Y/%m', verbose_name='封面图')),
                ('Raisemoney', models.IntegerField(default=0, verbose_name='筹集资金')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('participants', models.IntegerField(default=0, verbose_name='参与人数')),
                ('state', models.CharField(choices=[('jjks', '即将开始'), ('zcz', '众筹中'), ('zccz', '众筹成功')], max_length=5, verbose_name='状态')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='ProjectOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='分类')),
                ('desc', models.CharField(max_length=200, verbose_name='描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.AddField(
            model_name='projectmodels',
            name='ification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectOverview', verbose_name='所属分类'),
        ),
    ]
