# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-11 02:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('st', '科技'), ('design', '设计'), ('pw', '公益'), ('ag', '农业'), ('cu', '文化')], default='st', max_length=20, verbose_name='产品分类')),
                ('image', models.ImageField(upload_to='image/project/%Y/%m')),
                ('name', models.CharField(max_length=255, verbose_name='项目名称')),
                ('remark', models.CharField(max_length=255, verbose_name='标记')),
                ('money', models.BigIntegerField(verbose_name='目标金额')),
                ('day', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('status', models.CharField(choices=[('ready', '即将开始'), ('begin', '众筹中'), ('success', '众筹成功'), ('fail', '众筹失败')], default='ready', max_length=20, verbose_name='当前状态')),
                ('deploydate', models.DateField(default=datetime.datetime.now, verbose_name='部署时间')),
                ('supporter', models.IntegerField(verbose_name='支持人数')),
                ('supportmoney', models.BigIntegerField(verbose_name='支持金额')),
                ('completion', models.IntegerField(verbose_name='完成进度')),
                ('memberid', models.IntegerField(verbose_name='会员数')),
                ('createdate', models.DateField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('follower', models.IntegerField(verbose_name='众筹人数')),
            ],
            options={
                'verbose_name': '项目信息',
                'verbose_name_plural': '项目信息',
            },
        ),
        migrations.RemoveField(
            model_name='projectmodels',
            name='ification',
        ),
        migrations.DeleteModel(
            name='Projectmodels',
        ),
        migrations.DeleteModel(
            name='ProjectOverview',
        ),
    ]
