# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnSetting',
            fields=[
                ('r_num', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('r_type', models.CharField(choices=[('entity', '实物回报'), ('virtual', '虚拟物品回报')], max_length=10, verbose_name='回报类型')),
                ('support_money', models.CommaSeparatedIntegerField(max_length=10, verbose_name='支持金额')),
                ('r_content', models.CharField(max_length=200, verbose_name='回报内容')),
                ('r_image', models.ImageField(upload_to='image/project/%Y/%m', verbose_name='回报图片说明')),
                ('r_total', models.CharField(max_length=10, verbose_name='回报数量')),
                ('r_limit', models.CharField(choices=[('no', '不限购'), ('yes', '限购')], default='no', max_length=10, verbose_name='限购')),
                ('r_freight', models.CommaSeparatedIntegerField(max_length=10, verbose_name='运费')),
                ('r_invoice', models.CharField(choices=[('no', '不开发票'), ('yes', '可开发票')], default='no', max_length=10, verbose_name='发票')),
                ('r_date', models.CharField(max_length=10, verbose_name='回报时间')),
            ],
            options={
                'verbose_name_plural': '回报设置',
                'verbose_name': '回报设置',
            },
        ),
    ]
